import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald,",
    description:"The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan",
    categoryName: "fiction",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Trust",
    author: "Hernan Diaz",
    description:"",
    categoryName: "fiction",
    imgSrc:"",
    price: "3000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Beloved",
    author: "Toni Morrison",
    description:"",
    categoryName: "fiction",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Into thin air ",
    author: "Jon Krakauer",
    description:"",
    categoryName: "non-fiction",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "The Right Stuff",
    author: "Tom Wolfe",
    description:"",
    categoryName: "non-fiction",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Silent Spring",
    author: "Rachel Carson",
    description:"",
    categoryName: "non-fiction",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "It",
    author: "Stephen King",
    description:"",
    categoryName: "horror",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
    {
    _id: uuid(),
    title: "Frankenstein",
    author: "Mary Shelley",
    description:"",
    categoryName: "horror",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },  {
    _id: uuid(),
    title: "The Exorcist",
    author: "William Peter Blatty",
    description:"",
    categoryName: "horror",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Wuthering Heights",
    author: "Emily Brontë",
    description:"",
    categoryName: "Classics",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description:"",
    categoryName: "Classics",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Little Women",
    author: "Louisa May Alcotts",
    description:"",
    categoryName: "Classics",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "The Lord of the Rings",
    author: "J. R. R. Tolkien",
    description:"",
    categoryName: "Fantasy",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Dragonflight",
    author: "Anne McCaffrey",
    description:"",
    categoryName: "Fantasy",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Jade City",
    author: "Fonda Lee",
    description:"",
    categoryName: "Fantasy",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "It Ends with Us",
    author: "Colleen Hoover",
    description:"",
    categoryName: "romance",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Outlander",
    author: "Diana Gabaldon",
    description:"",
    categoryName: "romance",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Happy Place",
    author: "Emily Henry",
    description:"",
    categoryName: "romance",
    imgSrc:"",
    price: "5000",
    updatedPrice:"",
    rating:"",
    inStock:true,
    fastDelivery:"",
  },
];
