import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald,",
    description:"The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan",
    categoryName: "fiction",
    imgSrc:"https://m.media-amazon.com/images/I/71FTb9X6wsL._SY522_.jpg",
    price: "500",
    updatedPrice:"3000",
    rating:5,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Trust",
    author: "Hernan Diaz",
    description:"",
    categoryName: "fiction",
    imgSrc:"https://m.media-amazon.com/images/I/414Nfj4Ea9L._SY445_SX342_.jpg",
    price: "400",
    updatedPrice:"",
    rating:4,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Beloved",
    author: "Toni Morrison",
    description:"",
    categoryName: "fiction",
    imgSrc:"https://m.media-amazon.com/images/I/41Rdzbiqh7L._SY445_SX342_.jpg",
    price: "300",
    updatedPrice:"",
    rating:3,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Into thin air ",
    author: "Jon Krakauer",
    description:"",
    categoryName: "non-fiction",
    imgSrc:"https://m.media-amazon.com/images/I/81m25lFGUuL._SY522_.jpg",
    price: "200",
    updatedPrice:"",
    rating:2,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "The Right Stuff",
    author: "Tom Wolfe",
    description:"",
    categoryName: "non-fiction",
    imgSrc:"https://m.media-amazon.com/images/I/71QdCubaXVL._SY522_.jpg",
    price: "100",
    updatedPrice:"",
    rating:1,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Silent Spring",
    author: "Rachel Carson",
    description:"",
    categoryName: "non-fiction",
    imgSrc:"https://m.media-amazon.com/images/I/81Yza7XmfjL._SY522_.jpg",
    price: "500",
    updatedPrice:"",
    rating:2,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "It",
    author: "Stephen King",
    description:"",
    categoryName: "horror",
    imgSrc:"https://m.media-amazon.com/images/I/41Hi5I5ZjUL.jpg",
    price: "600",
    updatedPrice:"",
    rating:3,
    inStock:true,
    fastDelivery:"",
  },
    {
    _id: uuid(),
    title: "Frankenstein",
    author: "Mary Shelley",
    description:"",
    categoryName: "horror",
    imgSrc:"https://m.media-amazon.com/images/I/5127OtHzHuL.jpg",
    price: "700",
    updatedPrice:"",
    rating:4,
    inStock:true,
    fastDelivery:"",
  },  {
    _id: uuid(),
    title: "The Exorcist",
    author: "William Peter Blatty",
    description:"",
    categoryName: "horror",
    imgSrc:"https://m.media-amazon.com/images/I/41L4E1gopyL.jpg",
    price: "500",
    updatedPrice:"",
    rating:5,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Wuthering Heights",
    author: "Emily Brontë",
    description:"",
    categoryName: "Classics",
    imgSrc:"https://m.media-amazon.com/images/I/514jjttxNfL.jpg",
    price: "400",
    updatedPrice:"",
    rating:4,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description:"",
    categoryName: "Classics",
    imgSrc:"https://m.media-amazon.com/images/I/51HrCuHBn+L.jpg",
    price: "300",
    updatedPrice:"",
    rating:3,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Little Women",
    author: "Louisa May Alcotts",
    description:"",
    categoryName: "Classics",
    imgSrc:"https://m.media-amazon.com/images/I/61rU-cyluVL.jpg",
    price: "200",
    updatedPrice:"",
    rating:3,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "The Lord of the Rings",
    author: "J. R. R. Tolkien",
    description:"",
    categoryName: "Fantasy",
    imgSrc:"https://m.media-amazon.com/images/I/61cP8-CI40L._SY522_.jpg",
    price: "700",
    updatedPrice:"",
    rating:2,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Dragonflight",
    author: "Anne McCaffrey",
    description:"",
    categoryName: "Fantasy",
    imgSrc:"https://m.media-amazon.com/images/I/71k643jYdTL._AC_SY879_.jpg",
    price: "800",
    updatedPrice:"",
    rating:1,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Jade City",
    author: "Fonda Lee",
    description:"",
    categoryName: "Fantasy",
    imgSrc:"https://m.media-amazon.com/images/I/51o5fA1F2EL._SY445_SX342_.jpg",
    price: "900",
    updatedPrice:"",
    rating:2,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "It Ends with Us",
    author: "Colleen Hoover",
    description:"",
    categoryName: "romance",
    imgSrc:"https://m.media-amazon.com/images/I/81s0B6NYXML._SY522_.jpg",
    price: "1000",
    updatedPrice:"",
    rating:3,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Outlander",
    author: "Diana Gabaldon",
    description:"",
    categoryName: "romance",
    imgSrc:"https://m.media-amazon.com/images/I/91tjikkfB6L._SY522_.jpg",
    price: "800",
    updatedPrice:"",
    rating:4,
    inStock:true,
    fastDelivery:"",
  },
  {
    _id: uuid(),
    title: "Happy Place",
    author: "Emily Henry",
    description:"",
    categoryName: "romance",
    imgSrc:"https://m.media-amazon.com/images/I/71oWaTEjEkL._SY522_.jpg",
    price: "500",
    updatedPrice:"",
    rating:5,
    inStock:true,
    fastDelivery:"",
  },
];
